version: "3.8"
services:
  fastify_backend:
    container_name: stamp_ai_fastify_backend
    image: brunoa94/stamp-ai-fastify_backend
    build:
      context: .
    ports:
      - "3002:3002"
    env_file: .env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    hostname: postgres
    image: "postgres:13"
    ports:
      - "5432:5432"
    restart: always
    env_file: .env
    volumes:
      - fastify_volume:/var/lib/postgres/data

volumes:
  fastify_volume: {}
